# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maria Carvajal
subtitle: Holistic Digital Strategist
email: maria.carvajal.casado@gmail.com
description:
  - Nice to meet you! I’m Maria, a multipotentialite based in Barcelona. I solve comunication problems from reflection to execution. For me, marketing online, social media and web design are the tools to build your digital alter ego or brand in the digital world.
  - I love to help you to find your soul and voice and empower them.
bio:
  - I studied Audiovisual Communication. The love for aesthetics and the power of words are the two hemispheres of my creative brain. After few years working on TV, communication and coolhunting I decide to focus on the digital path to understant new tools to communicate to the world. I had the opportunity to learn and work in Marketing Online at the great agency Runroom.
  - After almost three years there, I had an idea and I decided to bring it to life and I started a new challenge as the founder of Otter.  Realising the importance of copy and the use of words to improve our lives and relation with others guided me to study and get certified on  Neurolinguistic Programming. I decided to start sharing my learnings and thoughts along this path as The Zen Freelancer.
# baseurl: "/mariacarvajal" # the subpath of your site, e.g. /blog
url: "http://mariacarvajal.es" # the base hostname & protocol for your site
links:
  - link: 
    - LinkedIn
    - https://www.linkedin.com/in/maria-carvajal-casado-278569143/
  - link:
    - Instagram
    - https://www.instagram.com/thezenfreelancer/
  - link:
    - Twitter
    - https://twitter.com/MariaCarvajalC
  - link:
    - Pinterest
    - https://es.pinterest.com/maria_carvajal/
post:
  image: https://cdn-images-1.medium.com/max/2000/1*iUGmW_Z-84p1AX8B0Xgy8A.jpeg
  url: https://medium.com/@Maria_Carvajal/the-importance-of-designing-your-own-emotional-workout-bc5a2f25fac7
  title: The importance of designing your own “emotional workout”
post_2:
  image: https://cdn-images-1.medium.com/max/2000/1*RkYdyo5wjHmqoL6FGFdu_g.jpeg
  url: https://medium.com/@Maria_Carvajal/great-things-take-time-how-im-navigate-my-startup-path-with-patience-instead-of-investors-188a322725dc
  title: (Great) Things take time. How I’m navigating my startup path with patience instead of investors.
work: I'm up for new projects and collaborations. I will love to chat with you about how I can help you. You can contact me anytime at maria.carvajal.casado@gmail.com
# Build settings
markdown: kramdown
