# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maria Carvajal
subtitle: Holistic Digital Strategist
email: maria.carvajal.casado@gmail.com
description:
  - Nice to meet you! I’m Maria, a multipotentialite (I have just discovered it in a TED Talk) based in Barcelona. I solve comunication problems from reflection to execution. For me, marketing online, social media and web design are the tools to build your digital alter ego or brand in the digital world.
  - I love to help you to find your soul and voice and empower them.
bio:
  - I studied Audiovisual Communication. The love for aesthetics and the power of words are the two hemispheres of my creative brain. After few years working on TV, stylism and coolhunting I decided to focus on the digital path to understand new tools to communicate to the world. I had the opportunity to learn and work in Online Marketing at Runroom. 
  - After almost three years there, I had an idea and I decided to bring it to life starting a new challenge as the founder of Otter. Realising the importance of copy and the use of words to improve our lives and relation with each other guided me to study and get certified on NLP. I decided to start sharing my learnings and thoughts along this path as The Zen Freelancer.
  - I love to work with other freelancers or brands. If you are looking for a holistic digital communicator you can reach me here.
# baseurl: "/mariacarvajal" # the subpath of your site, e.g. /blog
url: "http://mariacarvajal.es" # the base hostname & protocol for your site
links:
  - link: 
    - LinkedIn
    - https://www.linkedin.com/in/maria-carvajal-casado-278569143/
  - link:
    - Instagram
    - https://www.instagram.com/thezenfreelancer/
  - link:
    - Twitter
    - https://twitter.com/MariaCarvajalC
  - link:
    - Pinterest
    - https://es.pinterest.com/maria_carvajal/
post:
  image: https://cdn-images-1.medium.com/max/2000/1*RkYdyo5wjHmqoL6FGFdu_g.jpeg
  url: https://medium.com/@Maria_Carvajal/great-things-take-time-how-im-navigate-my-startup-path-with-patience-instead-of-investors-188a322725dc
  title: (Great) Things take time. How I’m navigating my startup path with patience instead of investors.

post_2:
  image: https://cdn-images-1.medium.com/max/2000/1*dROz4jf5v6e7Zet0NcOQ-g.jpeg
  url: https://medium.com/@Maria_Carvajal/be-grateful-of-your-imperfections-and-how-to-deal-with-your-perfectionism-when-its-on-fire-ccfbe10a1390
  title: “Be grateful of your imperfections” and how to deal with your perfectionism when it’s on fire.
work: I'm up for new projects and collaborations. I will love to chat with you about how I can help you. You can contact me anytime at maria.carvajal.casado@gmail.com
# Build settings
markdown: kramdown
